/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package emulador;

/**
 *
 * @author Luisito
 */
public class DescripcionMaquinal extends javax.swing.JFrame {

    /**
     * Creates new form Descripcion
     */
    public DescripcionMaquinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona:", "[MDR] << MM[MAR]", "MM[MAR] << [MDR] ", "[AC] << +000000 ", "[AC] << [-AC] ", "[AC]5 << [IR]2  -  [AC]4-2 << 000   -  [AC]1-0 << [IR]1-0", "[PC] << [PC] + 1 ", "[IR] << [MDR]", "[MAR] << [PC]", "[MAR] << [PC] + [IR]2-0 ", "[MAR] << [IR]2-0", "[MAR] << [MDR]2-0", "[PC] << [IR]2-0", "[PC] << [PC] + [IR]2-0", "[PC] << [MDR]2-0", "[AC] << [MDR]", "[MDR] << [AC]2-0", "[AC] << [AC] + [IR]2-0", "[AC] << [AC] – [IR]2-0", "[AC] << [AC] + [MDR]", "[AC] << [AC] – [MDR]", "MDR << DISP ", "DISP << MDR" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emulador/Captura de pantalla 2015-03-30 a la(s) 21.42.34.png"))); // NOI18N

        jLabel2.setText("Averigua sobre las instrucciones más importantes en ensamblador: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       setVisible(false);
       new Interfaz().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        preguntaCual();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void preguntaCual() {
        int seleccion = jComboBox1.getSelectedIndex();
        String texto1 = "[MDR] << MM[MAR]\n\nLectura de memoria";
        String texto2 = "MM[MAR] << [MDR]\n\nEscritura a memoria";
        String texto3 = "[AC] << +000000 \n\nInicializar el acumulador en 0";
        String texto4 = "[AC] << [-AC] \n\nCambiar el signo del valor del acumulador";
        String texto5 = "[AC]5 << [IR]2\n" +
                        "[AC]4-2 << 000\n" +
                        "[AC]1-0 << [IR]1-0\n\nCargar un dato inmediato al acumulador";
        String texto6 = "[PC] << [PC] + 1\n\nIncrementar el valor del PC";
        String texto7 = "[IR] << [MDR]\n\nTransferir el contenido del MDR al IR";
        String texto8 = "[MAR] << [PC]\n\nTransferir el contenido del PC al MAR";
        String texto9 = "[MAR] << [PC] + [IR]2-0\n\nTransferir al MAR una dirección relativa";
        String texto10 = "[MAR] << [IR]2-0 \n\nTransferir al MAR una dirección absoluta.";
        String texto11 = "[MAR] << [MDR]2-0\n\nTransferir una dirección del MDR al MAR. ";
        String texto12 = "[PC] << [IR]2-0\n\nTransferir una dirección absoluta del IR al PC.";
        String texto13 = "[PC] << [PC] + [IR]2-0\n\nTransferir una dirección relativa al PC";
        String texto14 = "[PC] << [MDR]2-0\n\nTransferir una dirección del MDR al PC.";
        String texto15 = "[AC] << [MDR]\n\nTransferir el contenido del MDR al acumulador.";
        String texto16 = "[MDR] << [AC]2-0\n\nTransferir el contenido del AC al MDR.";
        String texto17 = "[AC] << [AC] + [IR]2-0\n\nSumar un dato inmediato al acumulador.";
        String texto18 = "[AC] << [AC] – [IR]2-0\n\nRestar un dato inmediato al acumulador.";
        String texto19 = "[AC] << [AC] + [MDR]\n\nSumar el MDR al acumulador.";
        String texto20 = "[AC] << [AC] – [MDR]\n\nRestar el MDR al acumulador.";
        String texto21 = "MDR << DISP \n\n Carga el dato del dispositivo en el MDR.";
        String texto22 = "DISP << MDR\n\n Carga el dato del MDR en el dispositivo.";
        String textoDefault = "Lenguaje Maquinal\n\nEl lenguaje máquina es el lenguaje en sistema binario que puede "
                + "ejecutar una computadora y que es interpretado directamente por el procesador."
                + " La dificultad de estos lenguajes es que dependen directamente del procesador "
                + "de la computadora, es decir, cada procesador utiliza un lenguaje máquinal distinto que está "
                + "definido por su propio hardware.";
        switch (seleccion)
        {
            case 1:
                jTextArea1.setText(texto1);
                break;
            case 2:
                jTextArea1.setText(texto2);
                break;
            case 3:
                jTextArea1.setText(texto3);
                break;
            case 4:
                jTextArea1.setText(texto4);
                break;
            case 5:
                jTextArea1.setText(texto5);
                break;
            case 6:
                jTextArea1.setText(texto6);
                break; 
            case 7:
                jTextArea1.setText(texto7);
                break;
            case 8:
                jTextArea1.setText(texto8);
                break;
            case 9:
                jTextArea1.setText(texto9);
                break;
            case 10:
                jTextArea1.setText(texto10);
                break;
            case 11:
                jTextArea1.setText(texto11);
                break;
            case 12:
                jTextArea1.setText(texto12);
                break;
            case 13:
                jTextArea1.setText(texto13);
                break;
            case 14:
                jTextArea1.setText(texto14);
                break;
            case 15:
                jTextArea1.setText(texto15);
                break;
            case 16:
                jTextArea1.setText(texto16);
                break;
            case 17:
                jTextArea1.setText(texto17);
                break;
            case 18:
                jTextArea1.setText(texto18);
                break;
            case 19:
                jTextArea1.setText(texto19);
                break;
            case 20:
                jTextArea1.setText(texto20);
                break;
            case 21:
                jTextArea1.setText(texto21);
                break;
            case 22:
                jTextArea1.setText(texto22);
                break;
            default:
                jTextArea1.setText(textoDefault);
                break;
        }
    }
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DescripcionEnsamblador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DescripcionEnsamblador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DescripcionEnsamblador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DescripcionEnsamblador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DescripcionMaquinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
